#include "SAA1099.hh"

#include "DeviceConfig.hh"
#include "serialize.hh"

#include <algorithm>

namespace openmsx {

// The SAA1099 internally updates its generators at clock / 256.  SoundStar
// supplies an 8 MHz clock, yielding a 31.25 kHz native stream.
static constexpr unsigned NATIVE_FREQ = 8'000'000 / 256;

SAA1099::SAA1099(const DeviceConfig& config)
	: ResampledSoundDevice(config.getMotherBoard(), "SoundStar-SAA1099",
	                       "SAA1099", 6, NATIVE_FREQ, true)
{
	resetState();
	registerSound(config);
}

SAA1099::~SAA1099()
{
	unregisterSound();
}

void SAA1099::resetState()
{
	regs.fill(0);
	toneCounter.fill(1);
	toneLevel.fill(false);
	noiseCounter.fill(1);
	noiseLfsr.fill(0x3ffff);
	envelopeStep.fill(0);
	envelopeLeft.fill(16);
	envelopeRight.fill(16);
	soundEnabled = false;
}

void SAA1099::reset(EmuTime time)
{
	updateStream(time);
	resetState();
}

unsigned SAA1099::tonePeriod(unsigned channel) const
{
	auto octave = (regs[0x10 + channel / 2] >> ((channel & 1) * 4)) & 7;
	// The oscillator frequency doubles for every octave step. At the native
	// clock rate this is (511 - frequency) / 2^octave samples per half-wave.
	return std::max(1u, (511u - regs[0x08 + channel]) >> octave);
}

unsigned SAA1099::noisePeriod(unsigned noise) const
{
	auto frequency = (regs[0x16] >> (noise * 4)) & 3;
	if (frequency == 3) {
		// Noise source 0/1 follows tone channel 0/3 respectively.
		return tonePeriod(noise ? 3 : 0);
	}
	// Fixed noise frequencies are clock/256, clock/512 and clock/1024.
	return 1u << frequency;
}

void SAA1099::setEnvelope(unsigned group, unsigned value)
{
	const auto control = regs[0x18 + group];
	const bool disabled = value == 16;
	if (!disabled) {
		value &= (control & 0x10) ? 14 : 15; // 3-bit resolution masks the LSB.
	}
	for (unsigned ch = group * 3; ch < group * 3 + 3; ++ch) {
		envelopeLeft[ch] = value;
		envelopeRight[ch] = (!disabled && (control & 1)) ? (15 - value) : value;
	}
}

void SAA1099::stepEnvelope(unsigned group)
{
	const auto control = regs[0x18 + group];
	if (!(control & 0x80)) {
		setEnvelope(group, 16);
		return;
	}

	auto& step = envelopeStep[group];
	// The SAA1099 advances through 0..63 once, then repeats the second half.
	step = ((step + 1) & 0x3f) | (step & 0x20);
	const auto phase = step & 31;
	unsigned value = 0;
	switch ((control >> 1) & 7) {
	case 0: value = 0; break;                         // zero
	case 1: value = 15; break;                        // maximum
	case 2: value = (step < 16) ? (15 - step) : 0; break;
	case 3: value = 15 - (step & 15); break;
	case 4: value = (step < 16) ? step :
	                (step < 32) ? (31 - step) : 0; break;
	case 5: value = (phase < 16) ? phase : (31 - phase); break;
	case 6: value = (step < 16) ? step : 0; break;
	case 7: value = step & 15; break;
	}
	setEnvelope(group, value);
}

void SAA1099::selectRegister(unsigned reg, EmuTime time)
{
	reg &= 31;
	// External envelope clocks are generated by selecting their control
	// register, not by writing its data value.
	if (reg == 0x18 || reg == 0x19) {
		auto group = reg & 1;
		if (regs[0x18 + group] & 0x20) {
			updateStream(time);
			stepEnvelope(group);
		}
	}
}

void SAA1099::writeRegister(unsigned reg, uint8_t value, EmuTime time)
{
	reg &= 31;
	if (reg == 0x1c) {
		// Bit 0 is the global sound enable, bit 1 synchronously resets the
		// waveform generators.  The latter is used by software before playback.
		updateStream(time);
		regs[reg] = value;
		soundEnabled = value & 1;
		if (value & 2) {
			for (unsigned ch = 0; ch < 6; ++ch) {
				toneCounter[ch] = tonePeriod(ch);
			}
			toneLevel.fill(false);
		}
		return;
	}
	if (regs[reg] != value) {
		updateStream(time);
		regs[reg] = value;
		if (reg == 0x18 || reg == 0x19) {
			auto group = reg & 1;
			envelopeStep[group] = 0;
			setEnvelope(group, 16);
		}
	}
}

void SAA1099::generateChannels(std::span<float*> buffers, unsigned num)
{
	for (unsigned sample = 0; sample < num; ++sample) {
		std::array<bool, 6> toggled{};
		for (unsigned ch = 0; ch < 6; ++ch) {
			if (--toneCounter[ch] == 0) {
				toneCounter[ch] = tonePeriod(ch);
				toneLevel[ch] = !toneLevel[ch];
				toggled[ch] = true;
			}
		}
		if (toggled[1] && !(regs[0x18] & 0x20)) stepEnvelope(0);
		if (toggled[4] && !(regs[0x19] & 0x20)) stepEnvelope(1);

		if (!soundEnabled) continue;
		for (unsigned ch = 0; ch < 6; ++ch) {
			auto* buffer = buffers[ch];
			if (!buffer) continue;
			auto toneEnabled = (regs[0x14] >> ch) & 1;
			auto noiseEnabled = (regs[0x15] >> ch) & 1;
			auto noise = noiseLfsr[ch / 3] & 1;
			auto tone = unsigned(toneLevel[ch]);
			unsigned level = 0;
			if (noiseEnabled) {
				level = toneEnabled ? (noise ? (tone << 1) : tone) : noise;
			} else if (toneEnabled) {
				level = tone;
			}
			if (level == 0) continue;

			auto amplitude = regs[ch];
			auto left = amplitude & 15;
			auto right = amplitude >> 4;
			// Keep the sum of all six outputs below the normal mixer range.
			buffer[2 * sample + 0] += float(left * envelopeLeft[ch]) / (1440.0f * float(level));
			buffer[2 * sample + 1] += float(right * envelopeRight[ch]) / (1440.0f * float(level));
		}
		for (unsigned noise = 0; noise < 2; ++noise) {
			if (--noiseCounter[noise] == 0) {
				noiseCounter[noise] = noisePeriod(noise);
				// 18-bit polynomial x^18 + x^11 + x, with an XOR feedback tap.
				auto feedback = ((noiseLfsr[noise] & 0x20000) == 0) !=
			                ((noiseLfsr[noise] & 0x00400) == 0);
				noiseLfsr[noise] = ((noiseLfsr[noise] << 1) | unsigned(feedback)) & 0x3ffff;
			}
		}
	}
}

float SAA1099::getAmplificationFactorImpl() const
{
	// generateChannels() already produces normalized 0.0..1.0 samples.
	// SoundDevice's default assumes signed 16-bit sample units and would make
	// this output 32768 times too quiet.
	return 1.0f;
}

template<typename Archive>
void SAA1099::serialize(Archive& ar, unsigned /*version*/)
{
	ar.serialize("regs", regs,
	             "toneCounter", toneCounter,
	             "toneLevel", toneLevel,
	             "noiseCounter", noiseCounter,
	             "noiseLfsr", noiseLfsr,
	             "envelopeStep", envelopeStep,
	             "envelopeLeft", envelopeLeft,
	             "envelopeRight", envelopeRight,
	             "soundEnabled", soundEnabled);
}
INSTANTIATE_SERIALIZE_METHODS(SAA1099);

} // namespace openmsx
